# Generated by Django 3.1.3 on 2021-03-03 09:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='uniqueID',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
