# Generated by Django 3.1.3 on 2021-03-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_report_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='complaint_title',
            field=models.CharField(default=1, max_length=10000000),
            preserve_default=False,
        ),
    ]
